name: rl
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cloudpickle=3.1.1
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - deprecated=1.2.13
  - executing=0.8.3
  - expat=2.7.1
  - farama-notifications=0.0.4
  - filelock=3.20.0
  - fonttools=4.55.3
  - freetype=2.13.3
  - fsspec=2025.9.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gymnasium=0.28.1
  - icu=75.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - lcms2=2.12
  - lerc=4.0.0
  - libabseil=20250127.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcxx=21.1.2
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=2.0.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libtorch=2.5.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - llvm-openmp=21.1.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=1.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.5.4
  - opentelemetry-api=1.30.0
  - optree=0.14.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pillow=11.0.0
  - pip=25.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pygments=2.19.1
  - pyparsing=3.2.5
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - pytorch=2.5.1
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - sympy=1.13.3
  - tk=8.6.15
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - pygame==2.6.1

prefix: "/Users/sqlxx/mamba/envs/rl"
