name: rl
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.1
  - contourpy=1.3.3
  - cpython=3.13.9
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - filelock=3.20.0
  - fonttools=4.60.1
  - freetype=2.14.1
  - fsspec=2025.9.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=75.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=21.1.2
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libtiff=4.7.1
  - libtorch=2.8.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=1.0
  - numpy=2.3.3
  - openjpeg=2.5.4
  - openssl=3.5.4
  - optree=0.17.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pygments=2.19.1
  - pyparsing=3.2.5
  - python=3.13.7
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pytorch=2.8.0
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - stack_data=0.2.0
  - sympy=1.14.0
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zstd=1.5.7
  - pip:
    - Farama-Notifications==0.0.4
    - cloudpickle==3.1.1
    - gym-notices==0.1.0
    - gymnasium==1.2.1
    - pygame==2.6.1
    - tqdm==4.67.1

prefix: "/Users/sqlxx/mamba/envs/rl"
