name: rl
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - contourpy=1.3.3
  - cycler=0.12.1
  - filelock=3.20.0
  - fonttools=4.60.1
  - freetype=2.14.1
  - fsspec=2025.9.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gymnasium
  - ipykernel
  - jinja2=3.1.6
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcxx=21.1.2
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libtiff=4.7.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - llvm-openmp=21.1.2
  - markupsafe=3.0.3
  - matplotlib
  - matplotlib-base=3.10.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.5
  - nomkl=1.0
  - numpy
  - openjpeg=2.5.4
  - openssl=3.5.4
  - optree=0.17.0
  - packaging=25.0
  - pandas
  - pillow=11.3.0
  - pip
  - pthread-stubs=0.4
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pyparsing=3.2.5
  - python=3.12
  - python-dateutil=2.9.0.post0
  - qhull=2020.2
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - idna==3.11
    - pygame==2.6.1
    - requests==2.32.5
    - sympy==1.14.0
    - torch==2.2.2
    - torchaudio==2.2.2
    - torchvision==0.17.2
    - urllib3==2.6.3

